### ISSUE TITLE
Unable to use in wordpress +docker container

### ISSUE THREAD

**Issue by emanuellopes** [spatie/wordpress-ray#71]
Hi all,
I'm trying to use ray with wordpress running inside a docker-compose.yml file.

I've followed the documentation installed the wordpress plugin and tried also with spatie/ray package on my wordpress theme, but I'm unable to connect to application.

I tested a retested this a lot of times but with no success.

- I've the last version of plugin and the ray application
- I've define('WP_ENVIRONMENT_TYPE', 'local'); inside wp-config.php

I don't know if I'm missing something on my configuration, also I don't know were I should put the ray.php config file.

I did some debug on spatie/ray but the config folder is always null or empty, the documentation are not good for this.

```yaml
version: '3.4'
services:
  php:
    container_name: "wordpress"
    build:
      context: .
      dockerfile: 'Dockerfile'
      target: php
    user: "1001"
    expose:
        - "23517"
    extra_hosts: # <-- does no harm
        - "host.docker.internal:host-gateway" # <-- does no harm
    volumes:
      - static_files:/app/public/static:rw
      - ./theme:/app/public/static/wp-content/themes/theme
  nginx:
    image: nginx:stable
    user: "1001"
    depends_on:
      - php
    environment:
      PHP_SERVER_HOST: php
    ports:
      - "8888:8080"
    expose:
        - "23517"
    extra_hosts: # <-- does no harm
        - "host.docker.internal:host-gateway" # <-- does no harm
    volumes:
      - static_files:/app/public/static:rw
      - ./theme:/app/public/static/wp-content/themes/theme
volumes:
  static_files: {}
```
